### ISSUE TITLE
Update CODEOWNERS file if needed

### ISSUE THREAD

**Issue by hdamker** [camaraproject/CapabilitiesAndRuntimeRestrictions#1]
**Problem description**

CODEOWNERS file is set up with one initial codewoner (@gmuratk). 

**Expected action**

Create a pull request if further initial Codeowners need to be added.

**Additional context**

The repository is set up without branch protection to allow the work with only one codeowner.

> A Sandbox API Repository must have at least one Codeowner. If the Sandbox API Repository has two or more Codeowners the activation of branch protection rules is recommended.

To activate branch protection rules write a mail to adm@lists.camaraproject.org

**Comment by gmuratk** [comment]
Fixed with #4
